#!/vortexfs1/apps/anaconda3/2021.05/bin/python
# EASY-INSTALL-SCRIPT: 'python-louvain==0.15','community'
__requires__ = 'python-louvain==0.15'
__import__('pkg_resources').run_script('python-louvain==0.15', 'community')
