#!/bin/bash

#SBATCH --partition=scavenger
#SBATCH --job-name=bowtie2
#SBATCH	--mail-type=ALL
#SBATCH	--mail-user=mbaldes@mit.edu
#SBATCH	--ntasks=1
#SBATCH	--cpus-per-task=36
#SBATCH	--mem=180G
#SBATCH	--time=12:00:00
#SBATCH	--output=bowtie2_%j.log
#export OMP_NUM_THREADS=36

#Index human reference genome for use in bowtie2
bowtie2-build --threads 36 hg38.fa.gz hg38

#ISO Samples List
declare -a Samples=("2_2" "2_4" "2_10" "3_1" "3_3" "3_5" "3_4" "3_6" "3_9" "4_6" "4_7" "4_8" "2_5" "2_6" "2_7" "2_8" "2_9" "3_7" "3_8" "4_1" "4_2" "4_3" "4_4" "4_5")

#Loop through samples and perform bowtie2 with human genome as reference (hg38), returns reads that do not align with hg38 (human free reads)
for sample in ${Samples[@]}
do
bowtie2 --threads 36 --un-conc-gz /vortexfs1/omics/env-bio/collaboration/clean_room/output/bowtie2/${sample} --very-sensitive -x hg38 -1 /vortexfs1/omics/env-bio/collaboration/clean_room/output/${sample}/${sample}.cap2::adapter_removal.0a2556ed213e.adapter_removed.R1.fastq.gz -2 /vortexfs1/omics/env-bio/collaboration/clean_room/output/${sample}/${sample}.cap2::adapter_removal.0a2556ed213e.adapter_removed.R2.fastq.gz -S ${sample}.sam
done
