#!/bin/bash

#SBATCH --partition=compute
#SBATCH --job-name=checkm
#SBATCH	--mail-type=ALL
#SBATCH	--mail-user=mbaldes@mit.edu
#SBATCH	--ntasks=1
#SBATCH	--cpus-per-task=36
#SBATCH	--mem=180G
#SBATCH	--time=12:00:00
#SBATCH	--output=checkm_%j.log
#export OMP_NUM_THREADS=36


#ISO Sample Lists
declare -a ISO5=("2_2" "2_4" "2_10" "3_1" "3_3" "3_5" "3_4" "3_6" "3_9" "4_6" "4_7" "4_8")

declare -a ISO6=("2_5" "2_6" "2_7" "2_8" "2_9" "3_8" "4_1" "4_2" "4_3" "4_4")

#Run quality analysis for all bins with checkm
for sample in ${ISO5[@]}
do
checkm lineage_wf -t 36 --pplacer_threads 2 -x fa ISO5/bins/${sample}_BINS /vortexfs1/omics/env-bio/collaboration/clean_room/output/CheckM/ISO5/${sample}  
done

for sample in ${ISO6[@]}
do
checkm lineage_wf -t 36 --pplacer_threads 2 -x fa ISO6-8/bins/${sample}_BINS /vortexfs1/omics/env-bio/collaboration/clean_room/output/CheckM/ISO6-8/${sample} 
done
