#!/bin/bash

#SBATCH --partition=compute
#SBATCH --job-name=error_correction
#SBATCH	--mail-type=ALL
#SBATCH	--mail-user=mbaldes@mit.edu
#SBATCH	--ntasks=1
#SBATCH	--cpus-per-task=36
#SBATCH	--mem=180G
#SBATCH	--time=12:00:00
#SBATCH	--output=error_correction_%j.log
#export OMP_NUM_THREADS=36


#ISO Sample List
declare -a Samples=("2_2" "2_4" "2_10" "3_1" "3_3" "3_5" "3_4" "3_6" "3_9" "4_6" "4_7" "4_8" "2_5" "2_6" "2_7" "2_8" "2_9" "3_7" "3_8" "4_1" "4_2" "4_3" "4_4" "4_5")

#Error correct samples using spades
for sample in ${Samples[@]}
do
/vortexfs1/home/matthew.baldes/.conda/envs/Cap2/bin/spades.py --only-error-correction --meta -t 36 -1 /vortexfs1/omics/env-bio/collaboration/clean_room/output/bowtie2/human/${sample}.1.fq -2 /vortexfs1/omics/env-bio/collaboration/clean_room/output/bowtie2/human/${sample}.2.fq -o /vortexfs1/omics/env-bio/collaboration/clean_room/output/error_corrected/${sample}
done
