#!/bin/bash

#SBATCH --partition=compute
#SBATCH --job-name=prokka
#SBATCH	--mail-type=ALL
#SBATCH	--mail-user=mbaldes@mit.edu
#SBATCH	--ntasks=1
#SBATCH	--cpus-per-task=36
#SBATCH	--mem=180G
#SBATCH	--time=12:00:00
#SBATCH	--output=prokka_%j.log
#export OMP_NUM_THREADS=36

#Prokka annotation of quality bins, ISO5 3_3 was included even though it does not meet quality standards

#ISO Samples with quality bins 
declare -a ISO5=("3_3")

declare -a ISO6=("2_5" "2_7" "2_8" "3_8" "4_1" "4_3" "4_4")

for sample in ${ISO5[@]}
do
prokka --cpus 36 --prefix ${sample} --outdir /vortexfs1/omics/env-bio/collaboration/clean_room/output/gtdbtk/ISO5/${sample} /vortexfs1/omics/env-bio/collaboration/clean_room/output/CheckM/ISO5/qual_bins/${sample}/*.fa  
done

for sample in ${ISO6[@]}
do
prokka --cpus 36 --prefix ${sample} --outdir /vortexfs1/omics/env-bio/collaboration/clean_room/output/prokka/ISO6-8/${sample} /vortexfs1/omics/env-bio/collaboration/clean_room/output/CheckM/ISO6-8/qual_bins/${sample}/*.fa
done
