#!/bin/bash

#SBATCH --partition=scavenger
#SBATCH --job-name=bowtie2_mouse
#SBATCH	--mail-type=ALL
#SBATCH	--mail-user=mbaldes@mit.edu
#SBATCH	--ntasks=1
#SBATCH	--cpus-per-task=36
#SBATCH	--mem=180G
#SBATCH	--time=12:00:00
#SBATCH	--output=bowtie2__mouse_%j.log
#export OMP_NUM_THREADS=36

#Index mouse reference genome for use in bowtie2
bowtie2-build --threads 36 mm39.fa.gz mm39

#ISO Sample List
declare -a Samples=("2_2" "2_4" "2_10" "3_1" "3_3" "3_5" "3_4" "3_6" "3_9" "4_6" "4_7" "4_8" "2_5" "2_6" "2_7" "2_8" "2_9" "3_7" "3_8" "4_1" "4_2" "4_3" "4_4" "4_5")

#Loop through samples and remove reads that map to mouse genome (mm39), returns reads that do not align with mouse genome 
for sample in ${Samples[@]}
do
bowtie2 --threads 36 --un-conc-gz /vortexfs1/omics/env-bio/collaboration/clean_room/output/bowtie2/mouse/${sample}.fa.gz --very-sensitive -x mm39 -1 /vortexfs1/omics/env-bio/collaboration/clean_room/output/bowtie2/human/${sample}.1.fa.gz -2 /vortexfs1/omics/env-bio/collaboration/clean_room/output/bowtie2/human/${sample}.2.fa.gz -S ${sample}_mouse.sam
done
