#!/bin/bash

#SBATCH --partition=bigmem
#SBATCH --job-name=krakenbuild.qsub
#SBATCH --mail-type=ALL
#SBATCH --mail-user=anmeyer@whoi.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=400G
#SBATCH --time=24:00:00
#SBATCH --output=krakenbuild_%j.log
export OMP_NUM_THREADS=1

krakenuniq-build --db /vortexfs1/omics/env-bio/collaboration/clean_room/databases --threads 24 --kmer-len 31 --taxids-for-genomes --taxids-for-sequences
